FROM jenkinsci/blueocean
USER root
WORKDIR /root

# Install docker-compose
#RUN curl -L --fail https://github.com/docker/compose/releases/download/1.25.1/run.sh -o /usr/local/bin/docker-compose
RUN curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose

USER jenkins
WORKDIR /
